Closes #4: it's possible to launch more engines on the same machine with different corpora. Ports are retrieved automatically if none are provided.

diff --git a/server b/server
--- a/server
+++ b/server
@@ -1,39 +1,90 @@
 #!/bin/bash
 
-ca_port="$2"
-ms_port="$3"
-rs_port="$4"
+# Args validation
 
+function printerr {
+	>&2 echo "ERROR: invalid command"
+	>&2 echo
+	>&2 echo "Usage:"
+	>&2 echo "    $0 start [engine] [context-analyzer-port moses-decoder-port rest-api-port]"
+	>&2 echo "    $0 stop [engine]"
+	>&2 echo "    $0 status [engine]"
+}
+
+arg_engine="default"
+ca_port=
+ms_port=
+rs_port=
+
+case "$1" in
+	status)
+		if [ "$#" -gt "2" ]; then
+			printerr
+			exit 3
+		elif [ "$#" -eq "2" ]; then
+			arg_engine="$2"
+		fi
+	;;
+	stop)
+		if [ "$#" -gt "2" ]; then
+			printerr
+			exit 3
+		elif [ "$#" -eq "2" ]; then
+			arg_engine="$2"
+		fi
+	;;
+	start)
+		if [ "$#" -eq "5" ]; then
+			arg_engine="$2"
+			ca_port="$3"
+			ms_port="$4"
+			rs_port="$5"
+		elif [ "$#" -eq "4" ]; then
+			ca_port="$2"
+			ms_port="$3"
+			rs_port="$4"
+		elif [ "$#" -eq "2" ]; then
+			arg_engine="$2"
+		elif [ "$#" -ne "1" ]; then
+			printerr
+			exit 3
+		fi
+	;;
+	*)
+		printerr
+		exit 3
+	;;
+esac
+
+echo
+echo "[Engine: $arg_engine]"
+echo
+
+# Import environment
+
+__home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+source $__home/scripts/env.sh $arg_engine
+
+user="$(whoami)"
 if [ -z "$ca_port" ]; then
-	ca_port=7531
+	ports=($($scripts_dir/getfreeports.py))
+	
+	ca_port=${ports[0]}
+	ms_port=${ports[1]}
+	rs_port=${ports[2]}
 fi
-if [ -z "$ms_port" ]; then
-	ms_port=7532
-fi
-if [ -z "$rs_port" ]; then
-	rs_port=7533
-fi
-
-user="ubuntu"
-
-home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
-bin=$home/bin
-engines=$home/engines
-pids_dir=$engines/pids
-logs=$home/logs
-
-mkdir -p $pids_dir
 
 # Context Analyzer section
-ca_process_name="mmt-context-analyzer"
-ca_home=$home/bin/context-analyzer
-ca_classpath="$ca_home/context-analyzer.jar"
+ca_process_name="context-analyzer"
+ca_stdout_log="$engine_log_dir/$ca_process_name.out"
+ca_stderr_log="$engine_log_dir/$ca_process_name.err"
+ca_classpath="$context_analyzer_home/context-analyzer.jar"
 ca_main_class="net.translated.contextanalyzer.http.Server"
-ca_lucene_index=$engines/lucene/ca_index
-ca_stdout_log="$logs/$ca_process_name.out"
-ca_stderr_log="$logs/$ca_process_name.err"
+ca_pid_file="$engine_runtime_dir/$ca_process_name.pid"
 
-ca_pid_file="$pids_dir/$ca_process_name.pid"
+if [ ! -e "$ca_pid_file" ] ; then
+	touch "$ca_pid_file"
+fi
 
 java_home=$(dirname $(dirname $(readlink -e /usr/bin/javac)))
 jsvc=$(which jsvc)
@@ -46,25 +97,26 @@ jsvc_exec() {
 		cmd=
 	fi
 
-	$jsvc -home $java_home -cwd $ca_home -cp $ca_classpath -user $user -outfile $ca_stdout_log -errfile $ca_stderr_log -pidfile $ca_pid_file $cmd $ca_main_class $args
+	$jsvc -home $java_home -cwd $context_analyzer_home -cp $ca_classpath -user $user -outfile $ca_stdout_log -errfile $ca_stderr_log -pidfile $ca_pid_file $cmd $ca_main_class $args
 }
 
 # Moses decoder section
-ms_process_name="mmt-moses-decoder"
-ms_home=$home/bin/mosesdecoder
-ms_exec=$ms_home/moses
-ms_moses_ini_src=$engines/decoder/cfg/moses.ini
-ms_moses_ini=$engines/decoder/cfg/~moses.ini
-ms_log="$logs/$ms_process_name.log"
+ms_process_name="moses-decoder"
+ms_moses_ini_src=$engine_moses_dir/cfg/moses.ini
+ms_moses_ini=$engine_moses_dir/cfg/~moses.ini
+ms_log="$engine_log_dir/$ms_process_name.log"
+ms_pid_file="$engine_runtime_dir/$ms_process_name.pid"
 
-ms_pid_file="$pids_dir/$ms_process_name.pid"
+if [ ! -e "$ms_pid_file" ] ; then
+	touch "$ms_pid_file"
+fi
 
 moses_exec() {
 	case "$1" in
 		start)
-			rm -rf $ms_log
-			sed "s/__CONTEXT_ANALYZER_DOMAIN__/localhost:$ca_port/g" $ms_moses_ini_src > $ms_moses_ini
-			$ms_exec -f $ms_moses_ini --server --server-port $ms_port >> $ms_log 2>&1 &
+			rm -f $ms_log
+			sed "s/$CONTEXT_ANALYZER_PLACEHOLDER/localhost:$ca_port/g" $ms_moses_ini_src > $ms_moses_ini
+			$moses_home/bin/moses -f $ms_moses_ini --server --server-port $ms_port >> $ms_log 2>&1 &
 			echo "$!" > $ms_pid_file
 		;;
 		stop)
@@ -78,16 +130,14 @@ moses_exec() {
 }
 
 # REST interface section
-rs_process_name="mmt-rest-service"
-rs_exec=$home/bin/rest-client.py
-rs_log="$logs/$rs_process_name.log"
-
-rs_pid_file="$pids_dir/$rs_process_name.pid"
+rs_process_name="rest-service"
+rs_log="$engine_log_dir/$rs_process_name.log"
+rs_pid_file="$engine_runtime_dir/$rs_process_name.pid"
 
 rest_exec() {
 	case "$1" in
 		start)
-			$rs_exec $rs_port $ms_port >> $rs_log 2>&1 &
+			$scripts_dir/rest-client.py $rs_port $ms_port >> $rs_log 2>&1 &
 			echo "$!" > $rs_pid_file
 		;;
 		stop)
@@ -101,6 +151,7 @@ rest_exec() {
 }
 
 # Executing command
+
 case "$1" in
 	status)
 		ca_pid=$(head -n 1 $ca_pid_file 2>/dev/null)
@@ -124,14 +175,17 @@ case "$1" in
 	;;
 	start)
 		echo -n "Starting Context Analyzer on port $ca_port...   "
-		jsvc_exec -start -p $ca_port -i "$ca_lucene_index"
+		jsvc_exec -stop &> /dev/null
+		jsvc_exec -start -p $ca_port -i "$engine_context_analyzer_index_dir"
 		echo "DONE"
 
 		echo -n "Starting Moses Decoder on port $ms_port...   "
+		moses_exec stop &> /dev/null
 		moses_exec start
 		echo "DONE"
 
 		echo -n "Starting REST Interface on port $rs_port...   "
+		rest_exec stop &> /dev/null
 		rest_exec start
 		echo "DONE"
 	;;
@@ -147,32 +201,6 @@ case "$1" in
 		echo -n "Stopping REST Interface...   "
 		rest_exec stop
 		echo "DONE"
-	;;
-	restart)
-		echo -n "Restarting Context Analyzer on port $ca_port...   "
-		jsvc_exec -stop
-		jsvc_exec -start -p $ca_port -i "$ca_lucene_index"
-		echo "DONE"
-
-		echo -n "Restarting Moses Decoder on port $ms_port...   "
-		moses_exec stop
-		moses_exec start
-		echo "DONE"
-
-		echo -n "Restarting REST Interface on port $rs_port...   "
-		rest_exec stop
-		rest_exec start
-		echo "DONE"
-	;;
-	*)
-		>&2 echo "ERROR: invalid command"
-		>&2 echo
-		>&2 echo "Usage:"
-		>&2 echo "    $0 start [context-analyzer-port] [moses-decoder-port]"
-		>&2 echo "    $0 stop"
-		>&2 echo "    $0 status"
-		>&2 echo "    $0 restart [context-analyzer-port] [moses-decoder-port]"
-		exit 3
 	;;
 esac
 
